---
AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instance with kops and kubectl
Resources:
  kopsInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairParameter
      ImageId: !Ref AMIIdParameter
      InstanceType: !Ref InstanceTypeParameter
      Monitoring: false
      IamInstanceProfile: !Ref KopsRoleName
      SecurityGroupIds:
        - !Ref kopsSshSecurityGroup
      UserData: !Base64 |
        #!/bin/bash -ex
        exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
        yum update -y
        yum install -y git docker wget
        systemctl start docker
        cd /opt
        curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
        chmod +x ./kops
        mv kops /usr/local/bin/
        curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv kubectl /usr/local/bin/kubectl
        echo "export PATH=$PATH:/usr/local/bin/" >> ~/.bashrc
        echo "export NAME=demo.k8s.local" >> ~/.bashrc
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-kops-instance
  kopsSshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${AWS::StackName}-kops-ssh-sg
      GroupName: !Sub ${AWS::StackName}-kops-ssh-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-kops-ssh-sg
      VpcId: !Ref VPCIdParameter
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
      - t2.medium
    Description: Enter t2.micro, m1.small, or t2.medium. Default is t2.micro.
  KeyPairParameter:
    Type: String
    Default: barath_mac_pair
    Description: Enter valid region specific keypair to be associated with the instance
  VPCIdParameter:
    Type: String
    Description: Enter vpc id to be associated with the resources.
  AMIIdParameter:
    Type: String
    Description: choose the AMI to launch the instance.
  KopsRoleName:
    Type: String
    Description: provide the kops role

