---
AWSTemplateFormatVersion: 2010-09-09
Description: ec2 instances for ansible practice
Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairParameter
      ImageId: !Ref AMIIDParameter
      InstanceType: !Ref InstanceTypeParameter
      Monitoring: false
      SecurityGroupIds:
        - !Ref sshSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ansible-host-1
  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairParameter
      ImageId: !Ref AMIIDParameter
      InstanceType: !Ref InstanceTypeParameter
      Monitoring: false
      SecurityGroupIds:
        - !Ref sshSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ansible-host-2
  EC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairParameter
      ImageId: !Ref AMIIDParameter
      InstanceType: !Ref InstanceTypeParameter
      Monitoring: false
      SecurityGroupIds:
        - !Ref sshSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ansible-host-3
  sshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${AWS::StackName}-ansible-host-ssh-sg
      GroupName: !Sub ${AWS::StackName}-ansible-host-ssh-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ansible-host-ssh-sg
      VpcId: !Ref VPCIdParameter
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - t3.micro
    Description: Enter t2.micro, m1.small, or t2.medium. Default is t2.micro.
  KeyPairParameter:
    Type: String
    Description: Enter valid region specific keypair to be associated with the instance
  VPCIdParameter:
    Type: String
    Description: Enter vpc id to be associated with the resources.
  AMIIDParameter:
    Type: String
    Description: choose the AMI to launch the instance.
