---
AWSTemplateFormatVersion: 2010-09-09
Description: ec2 instance with ansible
Resources:
  ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairParameter
      ImageId: !Ref AMIIDParameter
      InstanceType: !Ref InstanceTypeParameter
      Monitoring: false
      SecurityGroupIds:
        - !Ref sshSecurityGroup
      UserData: !Base64 |
        #!/bin/bash -ex
        yum update -y
        sudo amazon-linux-extras install ansible2 -y # enable if ami is amazon linux
        yum install ansible
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ansible-workstation
  sshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${AWS::StackName}-ansible-workstation-sg
      GroupName: !Sub ${AWS::StackName}-ansible-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ansible-workstation-sg
      VpcId: !Ref VPCIdParameter
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
    Description: Enter t2.micro, m1.small, or t2.medium. Default is t2.micro.
  KeyPairParameter:
    Type: String
    Default: barath_mac_pair_ohio
    Description: Enter valid region specific keypair to be associated with the instance
  VPCIdParameter:
    Type: String
    Description: Enter vpc id to be associated with the resources.
  AMIIDParameter:
    Type: String
    Description: choose the AMI to launch the instance.
